"""The Lead entity: a generated opportunity backed by correlated Signals.

Leads are GENERATED by the correlation and rule engines from verified
Signals -- they are never collected directly from a source and never
represent an individual homeowner. Every Lead must cite the Signal IDs
that justify it and explain, in ``reasoning``, why those signals together
support the conclusion.
"""

from __future__ import annotations

import hashlib
from collections.abc import Sequence
from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from app.domain.enums import Country, LeadPriority, ServiceCategory, VerificationStatus
from app.domain.value_objects import EstimatedLocation
from app.utils.ids import new_id
from app.utils.time import utc_now

#: The mission requires leads to be generated only after *multiple* verified
#: signals support the conclusion -- a single signal is never sufficient.
MIN_SUPPORTING_SIGNALS = 2


def compute_lead_identity_key(
    lead_type: ServiceCategory, supporting_signal_ids: Sequence[UUID]
) -> str:
    """Return a deterministic identity for a Lead, independent of id ordering.

    Two Leads represent the same real-world opportunity if they share a
    ``lead_type`` and reference the exact same *set* of supporting
    Signals -- regardless of what order those ids happen to be listed
    in (``[3, 1, 2]`` and ``[2, 3, 1]`` must produce the same key). This
    mirrors ``app.verification.weather_bridge_dedup.compute_fingerprint``'s
    same "stable fingerprint of business identity" approach, and is what
    ``LeadModel.identity_key`` (a real, database-level unique column --
    see ``app.database.models.lead_model``) is populated from, so two
    concurrently-persisted Leads for the same evidence can never both
    commit.
    """
    sorted_ids = sorted(str(signal_id) for signal_id in supporting_signal_ids)
    raw = f"{lead_type.value}|{','.join(sorted_ids)}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


class Lead(BaseModel):
    """A generated opportunity for one of the four supported service categories.

    Attributes:
        id: Unique identifier for this lead.
        lead_type: Which service category this lead represents.
        supporting_signal_ids: IDs of the (already verified) Signals that
            justify this lead. Must contain at least
            :data:`MIN_SUPPORTING_SIGNALS` distinct entries.
        country: ISO country of the property this lead concerns.
        county: Estonian county (maakond).
        municipality: Estonian municipality (vald/linn).
        estimated_location: A deliberately coarse location estimate --
            never a precise, individually identifying address.
        estimated_confidence: Aggregate confidence, in [0.0, 1.0], that the
            underlying facts (the supporting signals) are accurate. This is
            distinct from ``intent_score`` and is derived from Signal-level
            confidence, never hardcoded.
        intent_score: The lead-scoring system's estimate, in [0.0, 1.0], of
            how strongly the correlated signals indicate a genuine need for
            ``lead_type`` service. Computed independently of
            ``estimated_confidence`` -- see app.lead_generation.scoring.
        priority: Operator-facing triage priority derived from
            ``intent_score`` and ``estimated_confidence``.
        reasoning: Human-readable explanation of why this lead exists,
            referencing the matched rule and supporting signals. Must never
            be empty -- a Lead without reasoning cannot be trusted.
        created_at: When this lead was generated. Timezone-aware.
        verification_status: Lifecycle state. Starts UNVERIFIED; only a
            LeadVerifier implementation may advance it.
    """

    model_config = ConfigDict(frozen=True, str_strip_whitespace=True)

    id: UUID = Field(default_factory=new_id)
    lead_type: ServiceCategory
    supporting_signal_ids: list[UUID] = Field(min_length=MIN_SUPPORTING_SIGNALS)
    country: Country = Country.ESTONIA
    county: str = Field(min_length=1)
    municipality: str = Field(min_length=1)
    estimated_location: EstimatedLocation
    estimated_confidence: float = Field(ge=0.0, le=1.0)
    intent_score: float = Field(ge=0.0, le=1.0)
    priority: LeadPriority
    reasoning: str = Field(min_length=10)
    created_at: datetime = Field(default_factory=utc_now)
    verification_status: VerificationStatus = VerificationStatus.UNVERIFIED

    @field_validator("supporting_signal_ids")
    @classmethod
    def _signal_ids_must_be_unique(cls, value: list[UUID]) -> list[UUID]:
        if len(set(value)) != len(value):
            raise ValueError("Lead.supporting_signal_ids must not contain duplicates.")
        return value

    @field_validator("created_at")
    @classmethod
    def _created_at_must_be_timezone_aware(cls, value: datetime) -> datetime:
        if value.tzinfo is None:
            raise ValueError("Lead.created_at must be timezone-aware.")
        return value

    @model_validator(mode="after")
    def _estimated_location_must_agree_with_top_level_location(self) -> Lead:
        if self.estimated_location.county.casefold() != self.county.casefold():
            raise ValueError("Lead.estimated_location.county must match Lead.county.")
        if self.estimated_location.municipality.casefold() != self.municipality.casefold():
            raise ValueError("Lead.estimated_location.municipality must match Lead.municipality.")
        return self

    def with_verification(self, status: VerificationStatus) -> Lead:
        """Return a copy of this lead with its verification status updated."""
        return self.model_copy(update={"verification_status": status})

    @property
    def identity_key(self) -> str:
        """This Lead's deterministic identity -- see :func:`compute_lead_identity_key`."""
        return compute_lead_identity_key(self.lead_type, self.supporting_signal_ids)
